# Generated by Django 5.2.7 on 2025-11-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
