# Generated by Django 5.2.7 on 2025-11-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost_contactmessage_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsize',
            name='custom_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.size'),
        ),
    ]
