# Generated by Django 5.2.7 on 2025-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
